services:
  obs-server:
    build:
      context: .
      args:
        - PNPM_APPROVE_BUILDS=true
    image: obs-server:latest
    container_name: obs-server
    restart: unless-stopped
    ports:
      - 7003:7003
    volumes:
      - ${VOLUME_OBS_PATH}:/app/volumes/obs
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PNPM_APPROVE_BUILDS=true
    command: ['pnpm', 'start']
